<?php


function pum_front_views_api() {
  return array('api' => 3.0);
}

function pum_front_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'pum_front'). '/views', '/.inc/');
  $views = array();
  civicrm_initialize();
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}
